### ISSUE TITLE
allow Umlaute / unicode in PDF metadata and PDF index encoding

### ISSUE THREAD

**Issue by polarvogel** [wbh-community/pandoc-wbh-template#59]
By changing `unicode=false` to `unicode=true` in the hypersetup section of the wbh.tex template, Umlaute will be displayed correctly in PDF metadata and PDF index

https://github.com/wbh-community/pandoc-wbh-template/blob/3f76c29d4bd979923bcf386e026be6fca4fcc2ab/wbh.tex#L182

![Unbenannt](https://user-images.githubusercontent.com/6965769/210373158-68ee83ea-4f0b-459e-af51-b5bcb13be3c3.PNG)

**Comment by polarvogel** [comment]
Already fixed with another solution: https://github.com/wbh-community/wbhdoc/commit/e1664d6d9bf44d2d712f16c92a502a8932629e9f

**Comment by kreativmonkey** [comment]
thanks for that, my test was wrong and i have to add your solution for the problem. now that will be work correctly!
